radius: 5
height-modifier: 2
enabled-by-default: true
require-discovery-by-default: true
require-permissions-by-default: false
multiworld-by-default: false
qt-from-anywhere: false
enable-economy: false
withdraw-from-player-not-bank: true
free-by-default: false
price-multiplier: 0.8
free-from-qts: false
