name: QuickTravel
main: com.live.toadbomb.QuickTravel.QuickTravel
version: 0.8
description: >
             Allows for fast multi-destination point-to-point travel with optional fees.
commands:
  qt:
    description: Provides access to the QuickTravel plugin.
    usage: /qt <location> - Warps you to the specified <location> if valid.
    permission: qt.user
    permission-message: You are not authorised to use this command.
permissions:
  qt.admin.*:
    description: Gives access to all QuickTravel admin commands.
    default: op
    children:
      qt.admin.create: true
      qt.admin.rename: true
      qt.admin.type: true
      qt.admin.radius: true
      qt.admin.cuboid: true
      qt.admin.move: true
      qt.admin.dest: true
      qt.admin.enable: true
      qt.admin.disable: true
      qt.admin.delete: true
      qt.admin.price: true
      qt.admin.free: true
      qt.admin.discovery: true
      qt.admin.perms: true
      qt.admin.multiworld: true
      qt.admin.list: true
      qt.admin.welcome: true
      qt.admin.cfg: true
      qt.admin.reload: true
  qt.admin.create:
    description: Gives access to /qt create
    default: false
  qt.admin.rename:
    description: Gives access to /qt rename
    default: false
  qt.admin.type:
    description: Gives access to /qt type
    default: false
  qt.admin.radius:
    description: Gives access to /qt radius
    default: false
  qt.admin.cuboid:
    description: Gives access to /qt cuboid
    default: false
  qt.admin.move:
    description: Gives access to /qt update
    default: false
  qt.admin.dest:
    description: Gives access to /qt dest
    default: false
  qt.admin.enable:
    description: Gives access to /qt enable
    default: false
  qt.admin.disable:
    description: Gives access to /qt disable
    default: false
  qt.admin.delete:
    description: Gives access to /qt delete
    default: false
  qt.admin.price:
    description: Gives access to /qt price
    default: false
  qt.admin.free:
    description: Gives access to /qt free
    default: false
  qt.admin.discovery:
    description: Gives access to /qt discovery
    default: false
  qt.admin.perms:
    description: Gives access to /qt perms
    default: false
  qt.admin.multiworld:
    description: Gives access to /qt multiworld
    default: false
  qt.admin.list:
    description: Gives access to /qt list
    default: false
  qt.admin.welcome:
    description: Gives access to /qt welcome
    default: false
  qt.admin.cfg:
    description: Gives access to /qt cfg
    default: false
  qt.admin.reload:
    description: Gives access to /qt reload
    default: false
  qt.use.*:
    description: Gives player permission to use/discover all QTs
    default: false
  qt.user:
    description: Enables use of the QuickTravel plugin.
    default: op
  qt.free:
    description: Enables user to travel for free to all QTs
    default: false
  qt.fromanywhere:
    description: Enables user to QT from anywhere, even when the qt-from-anywhere option is not enabled
    default: op
softdepend: [Vault,WorldEdit,Dynmap]